[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev:vite"
  targetPort = 8080
  port = 3000
  framework = "#custom"

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
